apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  name: skills-ingress
  namespace: skills-services
spec:
  rules:   
    - host: wahlgrens.tplinkdns.com
      http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 80
            path: /api
          - backend:
              serviceName: operations-service
              servicePort: 80
            path: /operations    
          - backend:
              serviceName: scheduledjobs-service
              servicePort: 80
            path: /scheduledjobs 
          - backend:
              serviceName: meetings-service
              servicePort: 80
            path: /meetings 
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 80
            path: /api
          - backend:
              serviceName: operations-service
              servicePort: 80
            path: /operations    
          - backend:
              serviceName: scheduledjobs-service
              servicePort: 80
            path: /scheduledjobs 
          - backend:
              serviceName: meetings-service
              servicePort: 80
            path: /meetings        
  # This section is only required if TLS is to be enabled for the Ingress
  # tls:
  #     - hosts:
  #         - www.example.com
  #       secretName: example-tls

