apiVersion: v2
name: api-gateway
description: A Helm chart for Kubernetes

home: https://github.com/bitnami/charts/tree/master/bitnami/consul
icon: https://bitnami.com/assets/stacks/consul/img/consul-stack-220x234.png
keywords:
  - discovering
  - configuring
  - services
maintainers:
  - email: developers@ntrada.se
    name: Ntrada
sources:
  - https://github.com/bitnami/bitnami-docker-consul
  - https://www.ntrada.io/
type: application
version: 1.0.0
appVersion: 1.0.0
